<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="renderer" content="webkit">
	<base href="<?= URL('/') ?>" />
	<title><?php echo H(T("站点行为分析平台"))?></title>
	<link rel="stylesheet" href="assets/css/bootstrap.css" />
	<link rel="stylesheet" href="assets/css/datetimepicker.css" />
	<link rel="stylesheet" type="text/css" href="assets/css/summary.css">
	<script data-main="assets/js/main.js" src="assets/js/require.js"></script>
	<link rel="shortcut icon" href="assets/img/favicon.png" type="image/png">
</head>
<body>
<div class="container">
     <div class="row">
	    <nav class="sidebar-menu">
			<div class="container">
		    <div class="row">
				<div class="col-xs-4 ">
				<img src="assets/img/brand.png" style="padding-top:30px;">
				</div>
				<div class="col-xs-7">
					<p style="font-size:19px;padding-top:29px;"><?php echo H(T("仪器控"))?></p>
				</div>
		    </div>
				<ul class="menu">
					<li class="active"><a href="/Summary/#loginpart"><?php echo H(T("访问信息概况"))?></a></li>
		        	<li><a href="/Summary/#section-2"><?php echo H(T("访问情况查询"))?></a></li>
		        	<li><a href="/Summary/#section-3"><?php echo H(T("访问信息"))?></a></li>
		        	<li><a href="/Summary/#section-4"><?php echo H(T("各地区访问情况"))?></a></li>
		        	<li><a href="/Summary/#section-5"><?php echo H(T("访客身份"))?></a></li>
	                <li><a href="/Summary/#section-6"><?php echo H(T("操作系统统计"))?></a></li>
	                <li><a href="/Summary/#section-7"><?php echo H(T("访客习惯统计"))?></a></li>
		        	<li><a href="/Summary/#section-8"><?php echo H(T("模块访问分析"))?></a></li>
		        	<li><a href="/Summary/#section-9"><?php echo H(T("访问行为分析"))?></a></li>
				</ul>
			</nav>
		</div>
		<div class="maincontent">
			<div class="col-xs-12">
				<p style="color:black;font-size:42px;padding-top:22px;padding-left:220px;"><?php echo H(T("Lims站点行为监测"))?></p>
			</div>
		   
			<div class="row" style="margin-top:10px;">
		        	<div id="loginpart">
		        	<h3><b><?php echo H(T("访问信息概况"))?></b></h3>
		            	<table class="table">
							<tr style="background-color:  #052963;font: '微软雅黑'; color:#ffffff;">
								<th></th>
								<th><?php echo H(T("访问量(PV)"))?></th>
								<th><?php echo H(T("访客数(UV)"))?></th>
								<th><?php echo H(T("平均访问时长(AVG)"))?></th>
								<th><?php echo H(T("IP数"))?></th>
							</tr>
							<tr>
								<td><?php echo H(T("今 日"))?></td>
								<td class="h4"><b><?=H($today_visit)?></b></td>
								<td class="h4"><b><?=H($today_user)?></b></td>
								<td class="h4"><b><?=H($today_avg_time)?></b></td>
								<td class="h4"><b><?=H($today_ip)?></b></td>	
							</tr>
							<tr>
								<td><?php echo H(T("昨 日"))?></td>
								<td><?=H($yday_visit)?></td>
								<td><?=H($yday_user)?></td>
								<td><?=H($yday_avg_time)?></td>
								<td><?=H($yday_ip)?></td>
							</tr>
							<tr>
								<td><?php echo H(T("近一周"))?></td>
								<td><?=H($week_visit)?></td>
								<td><?=H($week_user)?></td>
								<td><?=H($week_avg_time)?></td>
								<td><?=H($week_ip)?></td>
							</tr>
						</table>
					
		        	</div>
				    <div id="section-2">
				    <h3><b><i class="icon-user"></i><?php echo H(T("按时间查看访问量"))?></b></h3>
						<div class="form-group date_picker">
						    <div class="col-xs-6">
			            		<div class="input-group date form_date col-md-8" data-date="" data-date-format="dd MM yyyy" data-link-field="dtp_input1" data-link-format="yyyy-mm-dd hh:ii">
			                	<input class="form-control" id="dtstart" name="date" placeholder="Start Time" size="10" type="text" readonly >
			                    </div>
			                </div>
			                <div class="col-xs-6">
			                	<div class="input-group date form_date col-md-10" data-date="" data-date-format="dd MM yyyy" data-link-field="dtp_input2" data-link-format="yyyy-mm-dd hh:ii">
			                	<input class="form-control" id="dtend" name="date" placeholder="End Time" size="10" type="text" readonly >
			                	<span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
								
								<span class="input-group-addon">
									<span id="select" class="glyphicon glyphicon-ok"></span>
								</span>
			            		</div>
			            	</div>
							
						</div>
					

						<div id="line" style="height: 450px; margin-top:70px;"></div>
		
				    </div>
				    <div id="section-3" class="container">
						<h3><b><i class="icon-cogs"></i><?php echo H(T("访问信息"))?></b></h3>
						
							<table id="tab" class="table table-hover">
				                <thead>
				                    <tr>
				                    	<th><?php echo H(T("站点"))?></th>
				                        <th><?php echo H(T("省份"))?></th>
				                        <th><?php echo H(T("城市"))?></th>
				                        <th><?php echo H(T("访问IP"))?></th>
				                        <th><?php echo H(T("浏览器"))?></th>
				                        <th><?php echo H(T("浏览器版本"))?></th>
				                        <th><?php echo H(T("操作系统"))?></th>
				                        <th><?php echo H(T("设备种类"))?></th>
				                        <th><?php echo H(T("登录时间"))?></th>
				                    </tr>
				                </thead>
								<tbody id="login_tab">
						        </tbody>	
							</table>
							<div style="float:right">
								<nav>
								  <ul class="pagination">
								    <li>
								      <a href="#" aria-label="Previous">	
								        <span aria-hidden="true">&laquo;</span>
								      </a>
								    </li>
									    <?php for($i=1;$i<=$total_page;$i++): ?>
									    	<li><a class="page" href="javascript:void(0)"><?=$i?></a></li>
									    <?php endfor;?>
								    <li>
								      <a href="#" aria-label="Next">
								        <span aria-hidden="true">&raquo;</span>
								      </a>
								    </li>
								  </ul>
								</nav>
							</div>
				    </div>
				    <div id="section-4">
		                <div class="col-xs-12"  id="map" style="height: 600px;"></div>
					</div>
				    <div id="section-5">
		        	<h3><b><i class="icon-user"></i><?php echo H(T("访客身份"))?></b></h3>
		            	<table class="table">
							<tr style="background-color:  #052963;font: '微软雅黑';color:#ffffff;">
								<th><?php echo H(T("访客身份"))?></th>
								<th><?php echo H(T("访问次数"))?></th>
								<th><?php echo H(T("所占比例"))?></th>
							</tr>
							<tr>
								<td><?php echo H(T("老 师"))?></td>
								<td><?=H($teacher_num)?></td>
								<td><?=H($teacher_scale)?></td>
								
							</tr>
							<tr>
								<td><?php echo H(T("学 生"))?></td>
								<td><?=H($student_num)?></td>
								<td><?=H($student_scale)?></td>
							</tr>
							<tr>
								<td><?php echo H(T("其 他"))?></td>
								<td><?=H($other_num)?></td>
								<td><?=H($other_scale)?></td>
								
							</tr>
						</table>
		        	</div>

				    <div id="section-6">
					<h3><b><i class="icon-reorder"></i><?php echo H(T("操作系统统计"))?></b></h3>
		                <div class="col-xs-6"  id="pie3" style="height: 400px;"></div>
						<div class="col-xs-6"  id="charts2" style="height:400px"></div>
					</div>
					<div id="section-7">
					<h3><b><i class="icon-heart"></i><?php echo H(T("退出习惯"))?></b></h3>
		            	<table class="table">
		            	    <thead>
								<tr style="background-color:  #052963;font: '微软雅黑';color:#ffffff;">
									<th><?php echo H(T("退出方式"))?></th>
									<th><?php echo H(T("次数"))?></th>
									<th><?php echo H(T("所占比例"))?></th>
								</tr>
							</thead>
							<tbody>
								<?php foreach($logout as $value):?>
								<tr>
									<td><?=H($value['name'])?></td>
									<td><?=H($value['times'])?></td>
									<td><?=H($value['percentage'])?></td>
								</tr>
								<?php endforeach;?>
							</tbody>
						</table> 
						<h3><b><i class="icon-heart-empty"></i><?php echo H(T("访客使用设备习惯"))?></b></h3>
		            	<table class="table">
							<tr style="background-color:  #052963;font: '微软雅黑';color:#ffffff;">
								<th><?php echo H(T("设备类别"))?></th>
								<th><?php echo H(T("次数"))?></th>
								<th><?php echo H(T("所占比例"))?></th>
							</tr>
							<tr>
								<td><?php echo H(T("电   脑"))?></td>
								<td><?=H($desktop_num)?></td>
								<td><?=H($desktop_scale)?></td>

							</tr>
							<tr>
								<td><?php echo H(T("移动设备"))?></td>
								<td><?=H($mobile_num)?></td>
								<td><?=H($mobile_scale)?></td>
							</tr>
							<tr>
								<td><?php echo H(T("Robot"))?></td>
								<td><?=H($robot_num)?></td>
								<td><?=H($robot_scale)?></td>
							</tr>
						</table>
					</div>

				    <div id="section-8">
					<h3><b><i class="icon-dashboard"></i><?php echo H(T("模块访问分析"))?></b></h3>
		                <div id="line2" style="height:400px"></div><hr>
					</div>
					<div id="section-9">
					<h3><b><?php echo H(T("访问行为分析"))?></b></h3>
						<div class="btn-group select-module">
							 <div class="btn-group">
							    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
							    <?php echo H(T("常规"))?> 
							        <span class="caret"></span>
							    </button>
							    <ul class="dropdown-menu">
							        <li><a class="moduleselecter" href="/Summary/#section-9" data-module="people"> <?php echo H(T("成员目录"))?></a></li>
							        <li><a class="moduleselecter" href="/Summary/#section-9" data-module="labs"><?php echo H(T("课题组"))?></a></li>
							        <li><a class="moduleselecter" href="/Summary/#section-9" data-module="equipments"> <?php echo H(T("仪器目录"))?></a></li>
							        <li><a class="moduleselecter" href="/Summary/#section-9" data-module="roles"><?php echo H(T("权限管理"))?></a></li>
							        <li><a class="moduleselecter" href="/Summary/#section-9" data-module="calendars"><?php echo H(T("日历模块"))?></a></li>

							    </ul>
							</div>
	                        <div class="btn-group">
							    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
							    <?php echo H(T("管理"))?> 
							        <span class="caret"></span>
							    </button>
							    <ul class="dropdown-menu">
							        <li><a class="moduleselecter" href="/Summary/#section-9" data-module="gismon"> <?php echo H(T("地理监控"))?></a></li>
							        <li><a class="moduleselecter" href="/Summary/#section-9" data-module="achievements"><?php echo H(T("成果管理"))?></a></li>
							    </ul>
							</div>
							<div class="btn-group">
							    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
							    <?php echo H(T("其他"))?> 
							        <span class="caret"></span>
							    </button>
							    <ul class="dropdown-menu">
								    <li><a class="moduleselecter" href="/Summary/#section-9" data-module="nfs_share"> <?php echo H(T("文件系统"))?></a></li>
							        <li><a class="moduleselecter" href="/Summary/#section-9" data-module="messages"><?php echo H(T("消息中心"))?></a></li>
							        <li><a class="moduleselecter" href="/Summary/#section-9" data-module="announces"> <?php echo H(T("系统公告"))?></a></li>
							        <li><a class="moduleselecter" href="/Summary/#section-9" data-module="billing"><?php echo H(T("财务中心"))?></a></li>
							        <li><a class="moduleselecter" href="/Summary/#section-9" data-module="cers"> <?php echo H(T("CERS"))?></a></li>
							        <li><a class="moduleselecter" href="/Summary/#section-9" data-module="entrance"><?php echo H(T("门禁管理"))?></a></li>
						            <li><a class="moduleselecter" href="/Summary/#section-9" data-module="envmon"> <?php echo H(T("环境监控"))?></a></li>
							        <li><a class="moduleselecter" href="/Summary/#section-9" data-module="orders"><?php echo H(T("订单管理"))?></a></li>
							        <li><a class="moduleselecter" href="/Summary/#section-9" data-module="vendor"><?php echo H(T("供应商管理"))?></a></li>
							    </ul>
							</div>
						</div>
		                <div id="line3" style="height:400px;padding-top:5px;padding-bottom:5px;"></div><hr>
					</div>
		        </div>
		    </div>
	    </div>
    </div>
</body>
</html>
 
<script type="text/javascript">
require(['main'],function($){
	$('.menu').children('li').hover(function(event){
        $(this).siblings('.active').removeClass('active');
        $(this).addClass('active');
        })
	require(['bootstrap-datetimepicker.min', 'css!../css/datetimepicker.css'],function(){
			$('#dtstart').datetimepicker({ 
		   		format:'yyyy-mm-dd hh:ii',
		        weekStart: 1,
		        todayBtn:  1,
				autoclose: 1,
				todayHighlight: 1,
				startView: 2,
				forceParse: 0,
		        showMeridian: 1
			});
			$('#dtend').datetimepicker({ 
		   		format:'yyyy-mm-dd hh:ii',
		        weekStart: 1,
		        todayBtn:  1,
				autoclose: 1,
				todayHighlight: 1,
				startView: 2,
				forceParse: 0,
		        showMeridian: 1
			});

			$.ajax({
				type:'POST',
				url:'ajax/summary/page/',
				dataType:"json",
				data:{},
				success:function(data){	
					data = JSON.parse(data);
					var content = "";
					for(var i=0;i<data.length;i++){

						content += "<tr>";
						content += "<td>"+ data[i].source_name + "</td>";
						content += "<td>"+ data[i].province + "</td>";
						content += "<td>"+ data[i].city + "</td>";
						content += "<td>"+ data[i].address + "</td>";
						content += "<td>"+ data[i].browser + "</td>";
						content += "<td>"+ data[i].b_version + "</td>";
						content += "<td>"+ data[i].OS_type +"</td>";
						content += "<td>"+ data[i].device_type +"</td>";
						content += "<td>"+ data[i].dtstart +"</td>";
						content += "</tr>";
					}
			
					$('#login_tab').html(content);
				}
			})
			$('select').click();
			$('moduleselecter').click();
			$('.page').click(function(){

				var page = $(this).text();
				$.ajax({
					type:'POST',
					url:'ajax/summary/page/'+page,
					dataType:"json",
					data:{},
					success:function(data){
						data = JSON.parse(data);
						content ="";
						for(var i=0;i<data.length;i++){ 
							content += "<tr>";
							content += "<td>"+ data[i].source_name + "</td>";
							content += "<td>"+ data[i].province + "</td>";
							content += "<td>"+ data[i].city + "</td>";
							content += "<td>"+ data[i].address + "</td>";
							content += "<td>"+ data[i].browser + "</td>";
							content += "<td>"+ data[i].b_version + "</td>";
							content += "<td>"+ data[i].OS_type +"</td>";
							content += "<td>"+ data[i].dtstart +"</td>";
							content += "</tr>";
						}

						$('#login_tab').html(content);
					}
				})
			})
		});	
    })
</script>
<script type="text/javascript">
require(['main'], function($) {
		require(['echarts.min'], function (echarts) {

		//line是关于根据日期搜索显示访问量的
		var SearchChart = echarts.init(document.getElementById('line'));
		//pie3 charts2是关于用户操作系统的
		var countBrowserChart = echarts.init(document.getElementById('pie3'));
		var browserPie = echarts.init(document.getElementById('charts2'));
		var visitMap;
		//map 是关于各地区访问情况的
		$.get('../assets/json/china.json', function (chinaJson) {
			echarts.registerMap('china', chinaJson);
			visitMap = echarts.init(document.getElementById('map'));
	    });
		//line2 pie4是关于模块访问分析的
		var moduleChart = echarts.init(document.getElementById('line2'));
		//countActionChart 是关于访问行为分析的
		var countActionChart = echarts.init(document.getElementById('line3'));
	   $(function(){ 
			$.ajax({
				type:"POST",
				url:'ajax/summary/browseroption/',
				data:{},
				dataType:"json",
			    success:function(result){			   
				    data = JSON.parse(result);
			    	browserPie.setOption({
				        title: {
				            text: '用户各浏览器数量统计'
				        },
				        tooltip: {},
				        legend: {
				            data:['数量']
				        },
				        xAxis: {
				        	axisLabel: {
							    rotate: 60,
								show:true,
								interval: 0,
								},
				            data: data['name'],
				        },
				        yAxis: {},
				        series: [{
				            name: '用户类型',
				            type: 'bar',
				            data: data['count'],
				        }]
				    });
				}
			})
			//各地区访问情况
			$.ajax({
				type:"POST",
				url:'ajax/summary/mapvisit/',
				data:{},
				dataType:"json",
			    success:function(result){
			    var geoCoordMap = {
				    '海门':[121.15,31.89],
				    '鄂尔多斯':[109.781327,39.608266],
				    '招远':[120.38,37.35],
				    '舟山':[122.207216,29.985295],
				    '齐齐哈尔':[123.97,47.33],
				    '盐城':[120.13,33.38],
				    '赤峰':[118.87,42.28],
				    '青岛':[120.33,36.07],
				    '乳山':[121.52,36.89],
				    '金昌':[102.188043,38.520089],
				    '泉州':[118.58,24.93],
				    '莱西':[120.53,36.86],
				    '日照':[119.46,35.42],
				    '胶南':[119.97,35.88],
				    '南通':[121.05,32.08],
				    '拉萨':[91.11,29.97],
				    '云浮':[112.02,22.93],
				    '梅州':[116.1,24.55],
				    '文登':[122.05,37.2],
				    '上海':[121.48,31.22],
				    '攀枝花':[101.718637,26.582347],
				    '威海':[122.1,37.5],
				    '承德':[117.93,40.97],
				    '厦门':[118.1,24.46],
				    '汕尾':[115.375279,22.786211],
				    '潮州':[116.63,23.68],
				    '丹东':[124.37,40.13],
				    '太仓':[121.1,31.45],
				    '曲靖':[103.79,25.51],
				    '烟台':[121.39,37.52],
				    '福州':[119.3,26.08],
				    '瓦房店':[121.979603,39.627114],
				    '即墨':[120.45,36.38],
				    '抚顺':[123.97,41.97],
				    '玉溪':[102.52,24.35],
				    '张家口':[114.87,40.82],
				    '阳泉':[113.57,37.85],
				    '莱州':[119.942327,37.177017],
				    '湖州':[120.1,30.86],
				    '汕头':[116.69,23.39],
				    '昆山':[120.95,31.39],
				    '宁波':[121.56,29.86],
				    '湛江':[110.359377,21.270708],
				    '揭阳':[116.35,23.55],
				    '荣成':[122.41,37.16],
				    '连云港':[119.16,34.59],
				    '葫芦岛':[120.836932,40.711052],
				    '常熟':[120.74,31.64],
				    '东莞':[113.75,23.04],
				    '河源':[114.68,23.73],
				    '淮安':[119.15,33.5],
				    '泰州':[119.9,32.49],
				    '南宁':[108.33,22.84],
				    '营口':[122.18,40.65],
				    '惠州':[114.4,23.09],
				    '江阴':[120.26,31.91],
				    '蓬莱':[120.75,37.8],
				    '韶关':[113.62,24.84],
				    '嘉峪关':[98.289152,39.77313],
				    '广州':[113.23,23.16],
				    '延安':[109.47,36.6],
				    '太原':[112.53,37.87],
				    '清远':[113.01,23.7],
				    '中山':[113.38,22.52],
				    '昆明':[102.73,25.04],
				    '寿光':[118.73,36.86],
				    '盘锦':[122.070714,41.119997],
				    '长治':[113.08,36.18],
				    '深圳':[114.07,22.62],
				    '珠海':[113.52,22.3],
				    '宿迁':[118.3,33.96],
				    '咸阳':[108.72,34.36],
				    '铜川':[109.11,35.09],
				    '平度':[119.97,36.77],
				    '佛山':[113.11,23.05],
				    '海口':[110.35,20.02],
				    '江门':[113.06,22.61],
				    '章丘':[117.53,36.72],
				    '肇庆':[112.44,23.05],
				    '大连':[121.62,38.92],
				    '临汾':[111.5,36.08],
				    '吴江':[120.63,31.16],
				    '石嘴山':[106.39,39.04],
				    '沈阳':[123.38,41.8],
				    '苏州':[120.62,31.32],
				    '茂名':[110.88,21.68],
				    '嘉兴':[120.76,30.77],
				    '长春':[125.35,43.88],
				    '胶州':[120.03336,36.264622],
				    '银川':[106.27,38.47],
				    '张家港':[120.555821,31.875428],
				    '三门峡':[111.19,34.76],
				    '锦州':[121.15,41.13],
				    '南昌':[115.89,28.68],
				    '柳州':[109.4,24.33],
				    '三亚':[109.511909,18.252847],
				    '自贡':[104.778442,29.33903],
				    '吉林':[126.57,43.87],
				    '阳江':[111.95,21.85],
				    '泸州':[105.39,28.91],
				    '西宁':[101.74,36.56],
				    '宜宾':[104.56,29.77],
				    '呼和浩特':[111.65,40.82],
				    '成都':[104.06,30.67],
				    '大同':[113.3,40.12],
				    '镇江':[119.44,32.2],
				    '桂林':[110.28,25.29],
				    '张家界':[110.479191,29.117096],
				    '宜兴':[119.82,31.36],
				    '北海':[109.12,21.49],
				    '西安':[108.95,34.27],
				    '金坛':[119.56,31.74],
				    '东营':[118.49,37.46],
				    '牡丹江':[129.58,44.6],
				    '遵义':[106.9,27.7],
				    '绍兴':[120.58,30.01],
				    '扬州':[119.42,32.39],
				    '常州':[119.95,31.79],
				    '潍坊':[119.1,36.62],
				    '重庆':[106.54,29.59],
				    '台州':[121.420757,28.656386],
				    '南京':[118.78,32.04],
				    '滨州':[118.03,37.36],
				    '贵阳':[106.71,26.57],
				    '无锡':[120.29,31.59],
				    '本溪':[123.73,41.3],
				    '克拉玛依':[84.77,45.59],
				    '渭南':[109.5,34.52],
				    '马鞍山':[118.48,31.56],
				    '宝鸡':[107.15,34.38],
				    '焦作':[113.21,35.24],
				    '句容':[119.16,31.95],
				    '北京':[116.46,39.92],
				    '徐州':[117.2,34.26],
				    '衡水':[115.72,37.72],
				    '包头':[110,40.58],
				    '绵阳':[104.73,31.48],
				    '乌鲁木齐':[87.68,43.77],
				    '枣庄':[117.57,34.86],
				    '杭州':[120.19,30.26],
				    '淄博':[118.05,36.78],
				    '鞍山':[122.85,41.12],
				    '溧阳':[119.48,31.43],
				    '库尔勒':[86.06,41.68],
				    '安阳':[114.35,36.1],
				    '开封':[114.35,34.79],
				    '济南':[117,36.65],
				    '德阳':[104.37,31.13],
				    '温州':[120.65,28.01],
				    '九江':[115.97,29.71],
				    '邯郸':[114.47,36.6],
				    '临安':[119.72,30.23],
				    '兰州':[103.73,36.03],
				    '沧州':[116.83,38.33],
				    '临沂':[118.35,35.05],
				    '南充':[106.110698,30.837793],
				    '天津':[117.2,39.13],
				    '富阳':[119.95,30.07],
				    '泰安':[117.13,36.18],
				    '诸暨':[120.23,29.71],
				    '郑州':[113.65,34.76],
				    '哈尔滨':[126.63,45.75],
				    '聊城':[115.97,36.45],
				    '芜湖':[118.38,31.33],
				    '唐山':[118.02,39.63],
				    '平顶山':[113.29,33.75],
				    '邢台':[114.48,37.05],
				    '德州':[116.29,37.45],
				    '济宁':[116.59,35.38],
				    '荆州':[112.239741,30.335165],
				    '宜昌':[111.3,30.7],
				    '义乌':[120.06,29.32],
				    '丽水':[119.92,28.45],
				    '洛阳':[112.44,34.7],
				    '秦皇岛':[119.57,39.95],
				    '株洲':[113.16,27.83],
				    '石家庄':[114.48,38.03],
				    '莱芜':[117.67,36.19],
				    '常德':[111.69,29.05],
				    '保定':[115.48,38.85],
				    '湘潭':[112.91,27.87],
				    '金华':[119.64,29.12],
				    '岳阳':[113.09,29.37],
				    '长沙':[113,28.21],
				    '衢州':[118.88,28.97],
				    '廊坊':[116.7,39.53],
				    '菏泽':[115.480656,35.23375],
				    '合肥':[117.27,31.86],
				    '武汉':[114.31,30.52],
				    '大庆':[125.03,46.58]
				};			   
				    data = JSON.parse(result);
				    var convertData = function (data) {
				    var res = [];
				    for (var i = 0; i < data.length; i++) {
				        var geoCoord = geoCoordMap[data[i].name];
				        if (geoCoord) {
				            res.push({
				                name: data[i].name,
				                value: geoCoord.concat(data[i].value)
				            });
				        }
				    }
				    return res;
				    };
				   	visitMap.setOption({
				   		backgroundColor: '#052963',
				        title: {
				            text: '各地区用户访问概况',
				            subtext:'overview',
				            left:'center',
				            textStyle:{
				            	color:'#fff'
				            }  
				        },
				        tooltip: {
				        	trigger: 'item',
				        },
				        legend: {
					        orient: 'vertical',
					        y: 'bottom',
					        x:'right',
					        data:['visit time'],
					        textStyle: {
            					color: '#fff'
       						}
    					},
    					geo: {
					        map: 'china',
					        label: {
					            emphasis: {
					                show: false
					            }
					        },
					        roam: true,
					        itemStyle: {
					            normal: {
					                areaColor: '#323c48',
					                borderColor: '#111'
					            },
					            emphasis: {
					                areaColor: '#2a333d'
					            }
					        }
   						},
			  		    series : [
				        {
				            name: 'visit time',
				            type: 'scatter',
				            coordinateSystem: 'geo',
				            data: convertData(data),
				            symbolSize: function (val) {
				                return val[2] / 10;
				            },
				            label: {
				                normal: {
				                    formatter: '{b}',
				                    position: 'right',
				                    show: false
				                },
				                emphasis: {
				                    show: true
				                }
				            },
				            itemStyle: {
				                normal: {
				                    color: '#ddb926'
				                }
				            }
				        },
				        {
				            name: 'Top 5',
				            type: 'effectScatter',
				            coordinateSystem: 'geo',
				            data: convertData(data.sort(function (a, b) {
				                return b.value - a.value;
				            }).slice(0, 6)),
				            symbolSize: function (val) {
				                return val[2] / 10;
				            },
				            showEffectOn: 'render',
				            rippleEffect: {
				                brushType: 'stroke'
				            },
				            hoverAnimation: true,
				            label: {
				                normal: {
				                    formatter: '{b}',
				                    position: 'right',
				                    show: true
				                }
				            },
				            itemStyle: {
				                normal: {
				                    color: '#f4e925',
				                    shadowBlur: 10,
				                    shadowColor: '#333'
				                }
				            },
				            zlevel: 1
				        }
				    ]

                    })
			    }
			}) 
            //设备类型
            $.ajax({
				type:"POST",
				url:'ajax/summary/devicetype/',
				data:{},
				dataType:"json",
			    success:function(result){			   
				    data = JSON.parse(result);
				   	countBrowserChart.setOption({
				        title: {
				            text: '用户各操作系统数量统计',
				            x:'center'
				        },
				        tooltip: {
				        	trigger: 'item',
   							formatter: "{a} <br/>{b} : {c} ({d}%)"
				        },
				  		series : [{
				           	name: '访问来源',
				           	type: 'pie',
				           	radius : '55%',
				           	center: ['50%', '60%'],
				           	data: data
				        }],
           				itemStyle: {
			                emphasis: {
			                    shadowBlur: 10,
			                    shadowOffsetX: 0,
			                    shadowColor: 'rgba(0, 0, 0, 0.5)'
			                }
                    	}
                    })
			    }
			}) 
			//搜索日期为空的时候
		    $.ajax({
		    	type:"POST",
		    	url: 'ajax/summary/search/',
		    	data:{},
		    	success:function(result){
		    	data = JSON.parse(result);
		    	var visit_time = [];
	    		var visit_count = [];
				$(data).each(function(index, val){
				visit_time.push(val[0]);
		    	visit_count.push(val[1]);	
		    		SearchChart.setOption({
					    title : {
	        				text: '访问量数据概况',
	        				
	    				},
	    				tooltip : {
	        				trigger: 'axis'
	    				},
	    				toolbox: {
	        				show : true,
	        				feature : {
	            				mark : {show: true},
	            				dataView : {show: true, readOnly: false},
	            				magicType : {show: true, type: ['line', 'bar']},
	            				restore : {show: true},
	            				saveAsImage : {show: true}
	        				}
	    				},
	    				calculable : true,
	    				xAxis : [
	        			{
	            			type : 'category',
	            			axisLabel: {
						    rotate: 30,
							show:true,
							interval: 0,
							},
	            			boundaryGap : false,
	            			data : visit_time,
	        			}
	    				 ],
	   					yAxis : [
	        			{
	            			type : 'value',
	            			axisLabel : {
	                			formatter: '{value}'
	            			}
	        			}
	    			],
	    			series : [
		        		{
		            		name:'每日访问量',
		            		type:'line',
		            		data: visit_count,
		            		markPoint : {
		                	data : [
		                    	{type : 'max', name: '最大值'},
		                    	{type : 'min', name: '最小值'}
		                	]
		            	},
		            	markLine : {
		                	data : [
		                    	{type : 'average', name: '平均值'}
		                	]
		            	}
		        		}
		    		]
				});
				})
			}
			    	
		})
		    //根据选定时间输出日访问量
		    $('#select').click(
			function date_picker(){
		  	var startpicker = $('#dtstart').val();
		  	var endpicker = $('#dtend').val();
            
			    $.ajax({
			    	type:"POST",
			    	url: 'ajax/summary/search/',
			    	data:{
			    		startpicker,
			    		endpicker
			    	},
			    	success:function(result){
			    	data = JSON.parse(result);
			    	var visit_time = [];
		    		var visit_count = [];
					$(data).each(function(index, val){
					visit_time.push(val['day']);
			    	visit_count.push(val['count']);	
			    		SearchChart.setOption({
						    title : {
		        				text: '访问量数据概况',
		        				
		    				},
		    				tooltip : {
		        				trigger: 'axis'
		    				},
		    				toolbox: {
		        				show : true,
		        				feature : {
		            				mark : {show: true},
		            				dataView : {show: true, readOnly: false},
		            				magicType : {show: true, type: ['line', 'bar']},
		            				restore : {show: true},
		            				saveAsImage : {show: true}
		        				}
		    				},
		    				calculable : true,
		    				xAxis : [
		        			{
		            			type : 'category',
		            			axisLabel: {
							    rotate: 30,
								show:true,
								interval: 0,
								},
		            			boundaryGap : false,
		            			data : visit_time,
		        			}
		    				 ],
		   					yAxis : [
		        			{
		            			type : 'value',
		            			axisLabel : {
		                			formatter: '{value}'
		            			}
		        			}
		    			],
		    			series : [
			        		{
			            		name:'每日访问量',
			            		type:'line',
			            		data: visit_count,
			            		markPoint : {
			                	data : [
			                    	{type : 'max', name: '最大值'},
			                    	{type : 'min', name: '最小值'}
			                	]
			            	},
			            	markLine : {
			                	data : [
			                    	{type : 'average', name: '平均值'}
			                	]
			            	}
			        		}
			    		]
					});
				})
			}
			    	
			    })
		    })
            //根据选择模块显示对应操作数量
		    $('.moduleselecter').click(function () {
		    	//console.log($(this).data('module'))
		    	//$('.moduleselecter').data('module');
			    $.ajax({
			    	type:"POST",
			    	url: 'ajax/summary/searchaction/',
			    	data:{
			    		module: $(this).data('module')
			    	},
			    	success:function(result){

			    	data = JSON.parse(result);
			    		countActionChart.setOption({
						    title : {
		        				text: '用户行为概况',
		        				
		    				},
		    				tooltip : {
		        				trigger: 'axis'
		    				},
		    				toolbox: {
		        				show : true,
		        				feature : {
		            				mark : {show: true},
		            				dataView : {show: true, readOnly: false},
		            				magicType : {show: true, type: ['line', 'bar']},
		            				restore : {show: true},
		            				saveAsImage : {show: true}
		        				}
		    				},
		    				calculable : true,
		    				xAxis : [
		        			{
		            			type : 'category',
		            			axisLabel: {
							    rotate: 20,
								show:true,
								height:80,
								interval: 0,
								},
		            			boundaryGap : false,
		            			data : data['name'],
		        			}
		    				 ],
		    				grid: { // 控制图的大小，调整下面这些值就可以，
             					x: 40,
            					x2: 100,
             					y2: 130,// y2可以控制 X轴跟Zoom控件之间的间隔，避免以为倾斜后造成 label重叠到zoom上
         					},
		   					yAxis : [
		        			{
		            			type : 'value',
		            			axisLabel : {
		                			formatter: '{value}'
		            			}
		        			}
		    			],
		    			series : [
			        		{
			            		name:'本操作执行次数',
			            		type:'line',
			            		data: data['count'],
			            		markPoint : {
			                	data : [
			                    	{type : 'max', name: '最大值'},
			                    	{type : 'min', name: '最小值'}
			                	]
			            	},
			            	markLine : {
			                	data : [
			                    	{type : 'average', name: '平均值'}
			                	]
			            	}
			        		}
			    		]
					});
				}
			    })
		    })
            //访问行为统计	
			    $.ajax({
			    	type:"POST",
			    	url: 'ajax/summary/countaction/',
			    	data:{} ,
			    	dataType: "json",
			    	success:function(result){
			    	data = JSON.parse(result);
			    		countActionChart.setOption({
						    title : {
		        				text: '用户行为概况',
		        				
		    				},
		    				tooltip : {
		        				trigger: 'axis'
		    				},
		    				toolbox: {
		        				show : true,
		        				feature : {
		            				mark : {show: true},
		            				dataView : {show: true, readOnly: false},
		            				magicType : {show: true, type: ['line', 'bar']},
		            				restore : {show: true},
		            				saveAsImage : {show: true}
		        				}
		    				},
		    				calculable : true,
		    				xAxis : [
		        			{
		            			type : 'category',
		            			axisLabel: {
							    rotate: 20,
								show:true,
								height:80,
								interval: 0,
								},
		            			boundaryGap : false,
		            			data : data['name'],
		        			}
		    				 ],
		    				grid: { // 控制图的大小，调整下面这些值就可以，
             					x: 40,
            					x2: 100,
             					y2: 130,// y2可以控制 X轴跟Zoom控件之间的间隔，避免以为倾斜后造成 label重叠到zoom上
         					},
		   					yAxis : [
		        			{
		            			type : 'value',
		            			axisLabel : {
		                			formatter: '{value}'
		            			}
		        			}
		    			],
		    			series : [
			        		{
			            		name:'本操作执行次数',
			            		type:'line',
			            		data: data['count'],
			            		markPoint : {
			                	data : [
			                    	{type : 'max', name: '最大值'},
			                    	{type : 'min', name: '最小值'}
			                	]
			            	},
			            	markLine : {
			                	data : [
			                    	{type : 'average', name: '平均值'}
			                	]
			            	}
			        		}
			    		]
					});
				}
			
		    })
            
            //模块统计折线图
		    $.ajax({
		    	type:"POST",
		    	url: 'ajax/summary/countmodule/',
		    	data:{} ,
		    	dataType: "json",
		    	success:function(result){
		    		
		    		data = JSON.parse(result);

		    		moduleChart.setOption({
					    title : {
	        				text: '模块访问数据',
	        				
	    				},
	    				tooltip : {
	        				trigger: 'axis'
	    				},
	    				legend: {
	        				data:['访问次数']
	    				},
	    				toolbox: {
	        				show : true,
	        				feature : {
	            				mark : {show: true},
	            				dataView : {show: true, readOnly: false},
	            				magicType : {show: true, type: ['line', 'bar']},
	            				restore : {show: true},
	            				saveAsImage : {show: true}
	        				}
	    				},
	    				calculable : true,
	    				xAxis : [
	    				
	        			{
	            			type : 'category',
	            			    axisLabel: {
							    rotate: 60,
								show:true,
								interval: 0,
								},
			            	boundaryGap : false,
	            			data: data['module'],
	        			}
	    				 ],
	   					yAxis : [
	        			{
	            			type : 'value',
	            			axisLabel : {
	                			formatter: '{value}'
	            			}
	        			}
	    			],
	    			series : [
	        		{
	            		name:'访问量',
	            		type:'line',
	            		data: data['count'],
	            		markPoint : {
	                	data : [
	                    	{type : 'max', name: '最大值'},
	                    	{type : 'min', name: '最小值'}
	                	]
	            	},
	            	markLine : {
	                	data : [
	                    	{type : 'average', name: '平均值'}
	                	]
	            	}
	        		}
	    			]
					});

		    	}
		    })

	    });
	    
    })
})
</script>



