<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<base href="<?= URL('/') ?>" />
	<title>站点行为分析平台</title>
	<script src="assets/js/require.js" data-main="assets/js/main.js"></script>
	<link rel="stylesheet" href="assets/css/bootstrap.css" />
	<link rel="stylesheet" href="assets/css/bootstrap-datetimepicker.min.css" />
	<link rel="stylesheet" type="text/css" href="assets/css/bootstrap-table-expandable.css">
	<link rel="stylesheet" type="text/css" href="assets/css/summary.css">
	<link rel="shortcut icon" href="assets/img/favicon.png">
</head>
<body>
	<div class="row">
		<div class="col-xs-2 col-md-offset-3">
		<img src="assets/img/logo.png" style="padding-top:30px;">
		</div>
		<div class="col-xs-7">
			<p style="color:black;font-size:42px;padding-top:22px;"><?php echo H(T("Lims站点行为监测"))?></p>
		</div>
		</div>
    </div>
	<div class="row" style="margin-top:10px;">
		<div class="col-xs-2">
			<ul class="nav nav-tabs nav-stacked" id="myNav">
				<li class="active"><a href="/Summary/#loginpart">登录信息概况</a></li>
	        	<li><a href="/Summary/#section-2">访客属性</a></li>
	        	<li><a href="/Summary/#section-3">访客身份</a></li>
                <li><a href="/Summary/#section-4">操作系统统计</a></li>
                <li><a href="/Summary/#section-5">退出习惯统计</a></li>
	        	<li><a href="/Summary/#section-6">模块访问分析</a></li>
	        	<li><a href="/Summary/#section-7">访问行为分析</a></li>
			</ul>
		</div>
    	<div class="col-xs-10">
        	<div id="loginpart">
        	<h3><b>访问信息概况</b></h3>
            	<table class="table">
					<tr style="background-color:  #CCEEFF;font: '微软雅黑';">
						<th></th>
						<th>访问量(PV)</th>
						<th>访客数(UV)</th>
						<th>平均访问时长(AVG)</th>
						<th>IP数</th>
					</tr>
					<tr>
						<td>今 日</td>
						<td class="h4"><b><?=H($today_visit)?></b></td>
						<td class="h4"><b><?=H($today_user)?></b></td>
						<td class="h4"><b><?=H($today_avg_time)?></b></td>
						<td class="h4"><b><?=H($today_ip)?></b></td>	
					</tr>
					<tr>
						<td>昨 日</td>
						<td><?=H($yday_visit)?></td>
						<td><?=H($yday_user)?></td>
						<td><?=H($yday_avg_time)?></td>
						<td><?=H($yday_ip)?></td>
					</tr>
					<tr>
						<td>近一周</td>
						<td><?=H($week_visit)?></td>
						<td><?=H($week_user)?></td>
						<td><?=H($week_avg_time)?></td>
						<td><?=H($week_ip)?></td>
					</tr>
				</table>
			<div>
				<div id="line" style="height: 400px;"></div>
			</div>
        	</div>
        	<div id="section-2" class="container">
				<h3><b>访问信息</b></h3>
				
					<table id="tab"  class="table table-hover">
		                <thead>
		                    <tr>
		                    	<th>站点</th>
		                        <th>省份</th>
		                        <th>城市</th>
		                        <th>访问IP</th>
		                        <th>浏览器</th>
		                        <th>浏览器版本</th>
		                        <th>操作系统</th>
		                        <th>登录时间</th>
		                    </tr>
		                </thead>
						<tbody id="login_tab">
				        </tbody>	
					</table>
					<div style="float:right">
						<nav>
						  <ul class="pagination">
						    <li>
						      <a href="#" aria-label="Previous">	
						        <span aria-hidden="true">&laquo;</span>
						      </a>
						    </li>
							    <?php for($i=1;$i<=$total_page;$i++): ?>
							    	<li><a class="page" href="javascript:void(0)"><?=$i?></a></li>
							    <?php endfor;?>
						    <li>
						      <a href="#" aria-label="Next">
						        <span aria-hidden="true">&raquo;</span>
						      </a>
						    </li>
						  </ul>
						</nav>
					</div>
		    </div>
		    <div id="section-3" style="margin-top:-30px; margin-bottom:30px;">
        	<h3><b>访客身份</b></h3>
            	<table class="table">
					<tr style="background-color:  #CCEEFF;font: '微软雅黑';">
						<th>访客身份</th>
						<th>访问次数</th>
						<th>所占比例</th>
					</tr>
					<tr>
						<td>老 师</td>
						<td><?=H($teacher_num)?></td>
						<td><?=H($teacher_scale)?></td>
						
					</tr>
					<tr>
						<td>学 生</td>
						<td><?=H($student_num)?></td>
						<td><?=H($student_scale)?></td>
					</tr>
					<tr>
						<td>其 他</td>
						<td><?=H($other_num)?></td>
						<td><?=H($other_scale)?></td>
						
					</tr>
				</table>
        	</div>

		    <div id="section-4">
			<h3><b>操作系统统计</b></h3>
                <div class="col-xs-6"  id="pie3" style="height: 400px;"></div>
				<div class="col-xs-6"  id="charts2" style="height:400px"></div>
			</div>
			<div id="section-5">
			<h3><b>退出习惯</b></h3>
            	<table class="table">
					<tr style="background-color:  #CCEEFF;font: '微软雅黑';">
						<th>退出方式</th>
						<th>次数</th>
						<th>所占比例</th>
					</tr>
					<tr>
						<td>手 动</td>
						<td><?=H($manual_num)?></td>
						<td><?=H($manual_scale)?></td>
						
					</tr>
					<tr>
						<td>自 动</td>
						<td><?=H($auto_num)?></td>
						<td><?=H($auto_scale)?></td>
					</tr>
				</table>
			</div>

		    <div id="section-6">
			<h3><b>模块访问分析</b></h3>
                <div id="line2" style="height:400px"></div><hr>
			</div>
			 <div id="section-7">
			<h3><b>访问行为分析</b></h3>
                <div id="line3" style="height:400px"></div><hr>
			</div>
        </div>
    </div>

</body>
</html>
<script type="text/javascript">
require(['main'],function($){
	require(['bootstrap-table-expandable','bootstrap-datetimepicker.min'],function(){
	
		$("#myNav").affix({
			offset: { 
		    	top: 125 
				}
		});
		$.ajax({
			type:'POST',
			url:'ajax/summary/page/',
			dataType:"json",
			data:{},
			success:function(data){	
				data = JSON.parse(data);
				var content = "";
				for(var i=0;i<data.length;i++){

					content += "<tr>";
					content += "<td>"+ data[i].source_name + "</td>";
					content += "<td>"+ data[i].province + "</td>";
					content += "<td>"+ data[i].city + "</td>";
					content += "<td>"+ data[i].address + "</td>";
					content += "<td>"+ data[i].browser + "</td>";
					content += "<td>"+ data[i].b_version + "</td>";
					content += "<td>"+ data[i].OS_type +"</td>";
					content += "<td>"+ data[i].dtstart +"</td>";
					content += "</tr>";
				}
		
				$('#login_tab').html(content);
			}
		})
		$('#look').click();
		$('.page').click(function(){

			var page = $(this).text();
			$.ajax({
				type:'POST',
				url:'ajax/summary/page/'+page,
				dataType:"json",
				data:{},
				success:function(data){
					data = JSON.parse(data);
					content ="";
					for(var i=0;i<data.length;i++){ 
						content += "<tr>";
						content += "<td>"+ data[i].source_name + "</td>";
						content += "<td>"+ data[i].province + "</td>";
						content += "<td>"+ data[i].city + "</td>";
						content += "<td>"+ data[i].address + "</td>";
						content += "<td>"+ data[i].browser + "</td>";
						content += "<td>"+ data[i].b_version + "</td>";
						content += "<td>"+ data[i].OS_type +"</td>";
						content += "<td>"+ data[i].dtstart +"</td>";
						content += "</tr>";
					}

					$('#login_tab').html(content);
				}
			})
		})
	});	
})
</script>
<script type="text/javascript">
require(['main'], function($) {
	require(['echarts'], function (ec) {
		//line是关于每日访问量的
		var SummaryChart = ec.init(document.getElementById('line'));
		//pie3 charts2是关于用户操作系统的
		var countBrowserChart = ec.init(document.getElementById('pie3'));
		var browserPie = ec.init(document.getElementById('charts2'));
		//line2 pie4是关于模块访问分析的
		var moduleChart = ec.init(document.getElementById('line2'));
		//countActionChart 是关于访问行为分析的
		var countActionChart = ec.init(document.getElementById('line3'));
	   $(function(){ 
			$.ajax({
				type:"POST",
				url:'ajax/summary/browseroption/',
				data:{},
				dataType:"json",
			    success:function(result){
			   
			    	data = JSON.parse(result);

			    	countBrowserChart.setOption({
			    	title : {
	    				text: '用户操作系统',
	    				x:'center'
					},
					tooltip : {
	    				trigger: 'item',
	    				formatter: "{a} <br/>{b} : {c} ({d}%)"
					},
					legend: {
	    				orient: 'vertical',
	    				left: 'left',
	    				data: ['Window','Mac','Linux','Unix','Android','iOS','iPad','Windows Phone']
					},
				    series : [
				        {
				            name: '访问来源',
				            type: 'pie',
				            radius : '70%',
				            center: ['50%', '60%'],
				            data:[
				            	{value:data[1],name:"Window"},
				            	{value:data[2],name:"Mac"},
				            	{value:data[3],name:"Linux"},
				            	{value:data[4],name:"Unix"},
				            	{value:data[5],name:"Android"},
				            	{value:data[6],name:"iOS"},
				            	{value:data[7],name:"iPad"},
				            	{value:data[8],name:"Windows Phone"}
				            ],
				            itemStyle: {
				                emphasis: {
				                    shadowBlur: 10,
				                    shadowOffsetX: 0,
				                    shadowColor: 'rgba(0, 0, 0, 0.5)'
				                }
				            }
				        }
				    ]
			    })

			    	browserPie.setOption({
				        title: {
				            text: '用户各操作系统数量统计'
				        },
				        tooltip: {},
				        legend: {
				            data:['数量']
				        },
				        xAxis: {
				        	axisLabel: {
							    rotate: 60,
								show:true,
								interval: 0,
								},
				            data: ['Window','Mac','Linux','Unix','Android','iOS','iPad','Windows Phone']
				        },
				        yAxis: {},
				        series: [{
				            name: '用户类型',
				            type: 'bar',
				            data: [data[1],data[2],data[3],data[4],data[5],data[6],data[7],data[8]],
				        }]
				    });
			    }
			    
		  	})
		    //每日访问量 折线图	
			    $.ajax({
			    	type:"POST",
			    	url: 'ajax/summary/overview/',
			    	data:{} ,
			    	dataType: "json",
			    	success:function(result){
			    	data = JSON.parse(result);
			    	var visit_time = [];
		    		var visit_count = [];
					$(data).each(function(index, val){
					visit_time.push(val[0]);
			    	visit_count.push(val[1]);	
			    		SummaryChart.setOption({
						    title : {
		        				text: '访问量数据概况',
		        				
		    				},
		    				tooltip : {
		        				trigger: 'axis'
		    				},
		    				legend: {
		        				data:['今天','上周同一时间']
		    				},
		    				toolbox: {
		        				show : true,
		        				feature : {
		            				mark : {show: true},
		            				dataView : {show: true, readOnly: false},
		            				magicType : {show: true, type: ['line', 'bar']},
		            				restore : {show: true},
		            				saveAsImage : {show: true}
		        				}
		    				},
		    				calculable : true,
		    				xAxis : [
		        			{
		            			type : 'category',
		            			axisLabel: {
							    rotate: 55,
								show:true,
								interval: 0,
								},
		            			boundaryGap : false,
		            			data : visit_time,
		        			}
		    				 ],
		   					yAxis : [
		        			{
		            			type : 'value',
		            			axisLabel : {
		                			formatter: '{value}'
		            			}
		        			}
		    			],
		    			series : [
			        		{
			            		name:'每日访问量',
			            		type:'line',
			            		data: visit_count,
			            		markPoint : {
			                	data : [
			                    	{type : 'max', name: '最大值'},
			                    	{type : 'min', name: '最小值'}
			                	]
			            	},
			            	markLine : {
			                	data : [
			                    	{type : 'average', name: '平均值'}
			                	]
			            	}
			        		}
			    		]
					});
				})
			}
		    })
            
            //访问行为统计	
			    $.ajax({
			    	type:"POST",
			    	url: 'ajax/summary/countaction/',
			    	data:{} ,
			    	dataType: "json",
			    	success:function(result){
			    	data = JSON.parse(result);
			    		countActionChart.setOption({
						    title : {
		        				text: '用户行为概况',
		        				
		    				},
		    				tooltip : {
		        				trigger: 'axis'
		    				},
		    				toolbox: {
		        				show : true,
		        				feature : {
		            				mark : {show: true},
		            				dataView : {show: true, readOnly: false},
		            				magicType : {show: true, type: ['line', 'bar']},
		            				restore : {show: true},
		            				saveAsImage : {show: true}
		        				}
		    				},
		    				calculable : true,
		    				xAxis : [
		        			{
		            			type : 'category',
		            			axisLabel: {
							    rotate: 20,
								show:true,
								interval: 0,
								},
		            			boundaryGap : false,
		            			data : data['name'],
		        			}
		    				 ],
		   					yAxis : [
		        			{
		            			type : 'value',
		            			axisLabel : {
		                			formatter: '{value}'
		            			}
		        			}
		    			],
		    			series : [
			        		{
			            		name:'本操作执行次数',
			            		type:'line',
			            		data: data['count'],
			            		markPoint : {
			                	data : [
			                    	{type : 'max', name: '最大值'},
			                    	{type : 'min', name: '最小值'}
			                	]
			            	},
			            	markLine : {
			                	data : [
			                    	{type : 'average', name: '平均值'}
			                	]
			            	}
			        		}
			    		]
					});
				}
			
		    })
     
            //模块统计折线图
		    $.ajax({
		    	type:"POST",
		    	url: 'ajax/summary/line2option/',
		    	data:{} ,
		    	dataType: "json",
		    	success:function(result){
		    		
		    		data = JSON.parse(result);

		    		moduleChart.setOption({
					    title : {
	        				text: '模块访问数据',
	        				
	    				},
	    				tooltip : {
	        				trigger: 'axis'
	    				},
	    				legend: {
	        				data:['访问次数']
	    				},
	    				toolbox: {
	        				show : true,
	        				feature : {
	            				mark : {show: true},
	            				dataView : {show: true, readOnly: false},
	            				magicType : {show: true, type: ['line', 'bar']},
	            				restore : {show: true},
	            				saveAsImage : {show: true}
	        				}
	    				},
	    				calculable : true,
	    				xAxis : [
	    				
	        			{
	            			type : 'category',
	            			    axisLabel: {
							    rotate: 60,
								show:true,
								interval: 0,
								},
			            	boundaryGap : false,
	            			data: ['people','labs','equipments','roles','gismon',
	            			'achievements','nfs_share','messages','announces','billing','cers','entrance','envmon','orders','vendor','eq_charge','eq_sample','eq_reserv','nfs','wechat'],
	        			}
	    				 ],
	   					yAxis : [
	        			{
	            			type : 'value',
	            			axisLabel : {
	                			formatter: '{value}'
	            			}
	        			}
	    			],
	    			series : [
	        		{
	            		name:'访问量',
	            		type:'line',
	            		data: [data[1],data[2],data[3],data[4],data[5],data[6],data[7],data[8],data[9],data[10],data[11],data[12],data[13],data[14],data[15],data[16],data[17],data[18],data[19],data[20]],
	            		markPoint : {
	                	data : [
	                    	{type : 'max', name: '最大值'},
	                    	{type : 'min', name: '最小值'}
	                	]
	            	},
	            	markLine : {
	                	data : [
	                    	{type : 'average', name: '平均值'}
	                	]
	            	}
	        		}
	    			]
					});

		    	}
		    })

	    });
	    
    })
})
</script>



