
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<base href="<?= URL('/') ?>" />
	<title>站点行为分析平台</title>
	<script src="assets/js/require.js" data-main="assets/js/main.js"></script>
	<link rel="stylesheet" href="assets/css/bootstrap.css" />
	<link rel="stylesheet" href="assets/css/bootstrap-datetimepicker.min.css" />
	<link rel="stylesheet" type="text/css" href="assets/css/bootstrap-table-expandable.css">
	<link rel="stylesheet" type="text/css" href="assets/css/habit.css">
</head>
<body>
	<div>
		<h1>Habit Charts</h1>
	</div>
	<div class="row">
		<div class="col-xs-2">
			<ul class="nav nav-tabs nav-stacked" id="myNav">
				<li class="active"><a href="#">登录信息概况</a></li>
	        	<li><a href="#">访客属性</a></li>
	        	<li><a href="#">登出信息</a></li>
	        	<li><a href="#">系统环境</a></li>
	        	<li><a href="#">模块访问分析</a></li>
			</ul>
		</div>
        <div class="col-xs-10">
            <table class="table">
				<tr style="background-color: #FFC6C6;font: '微软雅黑';">
					<th></th>
					<th>访问量(PV)</th>
					<th>访客数(UV)</th>
				</tr>
				<tr>
					<td>今 日</td>
					<td class="h4"><b><?=H($today_visit)?></b></td>
					<td class="h4"><b><?=H($today_user)?></b></td>
				</tr>
				<tr>
					<td>昨 日</td>
					<td><?=H($yd_visit)?></td>
					<td><?=H($yd_user)?></td>
				</tr>
				
			</table>
        </div>

    </div>

</body>
</html>